- hosts: terraform-ansible
  tasks: 
  - name: Instalando o python3 e virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes # sempre executar o apt update 
    become: yes # informando a permissao root de usuario (sudo)
  - name: Instalando dependencias com pip (django e django rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
       - django
       - djangorestframework